services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "801:801"
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    extra_hosts:
      - "library.test:127.0.0.1"
    restart: always
